server:
  port: 8763

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8764/eureka/
    register-with-eureka: false
    fetch-registry: false
